# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_multiply_toDense <- function(X_, Y_) {
    .Call(`_JointGWAS_matrix_multiply_toDense`, X_, Y_)
}

partial_matrix_multiply_toDense <- function(X_, Y_, j) {
    .Call(`_JointGWAS_partial_matrix_multiply_toDense`, X_, Y_, j)
}

